# Generated by Django 4.1.7 on 2025-01-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název akce')),
                ('location', models.CharField(max_length=255, verbose_name='Místo konání')),
                ('date_time', models.DateTimeField(verbose_name='Čas konání')),
                ('description', models.TextField(verbose_name='Popis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Ilustrační obrázek')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Maximální kapacita')),
                ('status', models.CharField(choices=[('planned', 'Plánovaná'), ('ongoing', 'Probíhá'), ('completed', 'Dokončená')], default='planned', max_length=20, verbose_name='Stav')),
                ('open_until', models.DateTimeField(blank=True, null=True, verbose_name='Přihlášení otevřeno do')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Dodatečné poznámky')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Organizátor')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum potvrzení účasti')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
