# Generated by Django 4.1.7 on 2023-07-02 20:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='title', unique_with=('pub_date__month',)),
        ),
    ]
