# Generated by Django 4.1.7 on 2023-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
