# Generated by Django 4.1.7 on 2025-01-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název dokumentu')),
                ('file', models.FileField(upload_to='shared_documents/', verbose_name='Soubor')),
                ('document_type', models.CharField(choices=[('general', 'Obecné'), ('meeting', 'Zápisy z jednání')], default='general', max_length=10, verbose_name='Typ dokumentu')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno dne')),
            ],
        ),
    ]
